- name: npm-globals >> Installing Yarn
  community.general.npm:
    name: yarn
    global: yes

- name: npm-globals >> Installing ESLint
  community.general.npm:
    name: eslint
    global: yes

- name: npm-globals >> Installing Typescript Language Server
  community.general.npm:
    name: typescript-language-server
    global: yes

- name: npm-globals >> Installing Typescript
  community.general.npm:
    name: typescript
    global: yes

- name: npm-globals >> Installing TS-Node
  community.general.npm:
    name: ts-node
    global: yes

