- name: environment >> Creating $HOME/.local/
  ansible.builtin.file:
    dest: "{{ homedir }}/.local"
    mode: 0755
    owner: "{{ username }}"
    state: directory

- name: environment >> Creating $HOME/.config/
  ansible.builtin.file:
    dest: "{{ homedir }}/.config"
    mode: 0754
    owner: "{{ username }}"
    state: directory

- name: environment >> Checking for .dotfiles in $HOME 
  ansible.builtin.stat:
    path: "{{ homedir }}/.dotfiles"
  register: dotfiles

- name: environment >> Cloning .dotfiles if not exists
  ansible.builtin.git:
    repo: "https://github.com/joaopedropsilva/.dotfiles.git"
    dest: "{{ homedir }}/.dotfiles"
  when: dotfiles.stat.exists == False

- name: environment >> Stow packages into $HOME
  ansible.builtin.shell: "cd {{ homedir }}/.dotfiles/packages && stow --adopt --dotfiles -t {{ homedir }} */"

