- name: packages >> Installing core packages
  become: yes
  ansible.builtin.package:
    name:
      - git
      - stow
      - tmux
      - base
      - base-devel
      - i3
      - docker
      - docker-compose
      - curl
      - fzf
      - httpie
      - ripgrep
      - neofetch
      - neovim
      - python-passlib
      - rust
      - xclip
      - tldr
      - man-db
      - zip
      - unzip
      - unrar
      - gzip
      - tar
    state: present

