# General config
set -g base-index 1
set -g mouse on
setw -g mode-keys vi

# Binds
unbind C-b
set -g prefix C-a
bind C-a send-prefix
bind '-' split-window -h
bind '+' split-window -v
bind r source-file ~/.config/tmux/tmux.conf \; display "TMUX CONFIG RELOADED"
bind-key -r i run-shell "tmux neww tmux-cht.sh"

# Widgets
wg_prefix=" #{?client_prefix,<Prefix>,}"
wg_time=" #[fg=color220,bold,italics,bg=default]%H:%M#[none]"
wg_date=" #[fg=color231,bold,bg=default]%d/%b/%Y"
set -g status-right "${wg_prefix}${wg_time}${wg_date}"

# Appearance
set -g status-style fg=color241,bg=color233

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'

run '~/.tmux/plugins/tpm/tpm'

