[window]
padding = { x = 2, y =2 }
opacity = 0.75
decorations_theme_variant = "Dark"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }
size = 12
