- name: nodejs >> Installing npm
  become: yes
  ansible.builtin.package:
    name: npm
    state: present

- name: nodejs >> Creating npm global prefix
  ansible.builtin.file:
    path: "/home/{{ username }}/.local/.npm-global"
    state: directory
    mode: 0755

- name: nodejs >> Setting npm global prefix
  shell: "npm config set prefix /home/{{ username }}/.local/.npm-global"

- name: nodejs >> Installing N (Node Version Manager)
  community.general.npm:
    name: n
    global: yes

- name: nodejs >> Installing node lts
  shell: "/home/{{ username }}/.local/.npm-global/bin/n lts"

