# General config
set -g base-index 1
set -g mouse on
setw -g mode-keys vi

# Binds
bind '-' split-window -h
bind '=' split-window -v
bind r source-file ~/.config/tmux/tmux.conf \; display "TMUX CONFIG RELOADED"
bind-key -r i run-shell "tmux neww tmux_cht.sh"

# Widgets
wg_prefix=" #{?client_prefix,<Prefix>,}"
wg_sentence=" #[fg=color75,bold,italics,bg=default]keep pushin'#[none]"
wg_time=" #[fg=color220,bold,italics,bg=default]%H:%M#[none]"
wg_date=" #[fg=color231,bold,bg=default]%d/%b/%Y"
set -g status-right "${wg_prefix}${wg_sentence}${wg_time}${wg_date}"

# Appearance
set -g status-style fg=color241,bg=color233

