- name: general_configs >> Creating $HOME/.local/
  ansible.builtin.file:
    dest: "{{ homedir }}/.local"
    mode: 0755
    owner: "{{ username }}"
    state: directory

- name: general_configs >> Creating $HOME/.config/
  ansible.builtin.file:
    dest: "{{ homedir }}/.config"
    mode: 0754
    owner: "{{ username }}"
    state: directory

- name: general_configs >> Creating $HOME/.ssh/
  ansible.builtin.file:
    dest: "{{ homedir }}/.ssh"
    mode: 0700
    owner: "{{ username }}"
    state: directory

- name: general_configs >> Installing private member of ssh key
  ansible.builtin.copy:
    src: "{{ source_key_file }}"
    dest: "{{ dest_key_file }}"
    mode: 0600
    owner: "{{ username }}"

- name: general_configs >> Installing public member of ssh key
  ansible.builtin.copy:
    src: "{{ source_key_file }}.pub"
    dest: "{{ dest_key_file }}.pub"
    mode: 0644
    owner: "{{ username }}"

- name: general_configs >> Stow packages into $HOME
  ansible.builtin.shell:
    "cd {{ homedir }}/.dotfiles/packages && stow -t {{ homedir }} */"

